### ISSUE TITLE
OptionsProberManager - Error1

### ISSUE THREAD

**Issue by summitrabz** [yeti-switch/sems-yeti#6]
Hi, I was trying to build from source (1.11.10) on deb10 as per the instructon but ran into an error below:

compilation terminated.
make[3]: *** [CMakeFiles/sems_yeti.dir/build.make:157: CMakeFiles/sems_yeti.dir/src/OptionsProberManager.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/opt/sems-yeti/build'
make[2]: *** [CMakeFiles/Makefile2:76: CMakeFiles/sems_yeti.dir/all] Error 2
make[2]: Leaving directory '/opt/sems-yeti/build'
make[1]: *** [Makefile:133: all] Error 2
make[1]: Leaving directory '/opt/sems-yeti/build'
dh_auto_build: cd build && make -j4 returned exit code 2
make: *** [debian/rules:9: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b -j4 failed

**Comment by dmitry-sinina** [comment]
There is no enough data to say anything. Could you show more log lines?

**Comment by summitrabz** [comment]
Sorry @dmitry-sinina I over looked your response.. Here are the log below:

cat /etc/issue
Debian GNU/Linux 10 \n \l

root@rtp-sems:/opt/yeti-sems/sems-yeti# ls -la
total 56
drwxr-xr-x 9 root root 4096 Apr  5 03:33 .
drwxr-xr-x 3 root root 4096 Apr  5 03:32 ..
drwxr-xr-x 2 root root 4096 Apr  5 03:32 ci
drwxr-xr-x 2 root root 4096 Apr  5 03:32 cmake
-rw-r--r-- 1 root root 2588 Apr  5 03:32 CMakeLists.txt
drwxr-xr-x 2 root root 4096 Apr  5 03:37 debian
drwxr-xr-x 2 root root 4096 Apr  5 03:32 etc
drwxr-xr-x 8 root root 4096 Apr  5 03:32 .git
drwxr-xr-x 3 root root 4096 Apr  5 03:32 .github
-rw-r--r-- 1 root root  168 Apr  5 03:32 .gitignore
-rw-r--r-- 1 root root  452 Apr  5 03:32 Makefile
-rw-r--r-- 1 root root  992 Apr  5 03:32 README.md
-rw-r--r-- 1 root root 2144 Apr  5 03:33 sems-yeti-build-deps_1.0_all.deb
drwxr-xr-x 8 root root 4096 Apr  5 03:32 src
root@rtp-sems:/opt/yeti-sems/sems-yeti# debuild -us -uc -b -j$(nproc)
 dpkg-buildpackage -us -uc -ui -b -j4
dpkg-buildpackage: info: source package sems-yeti
dpkg-buildpackage: info: source version 1.12.18
dpkg-buildpackage: info: source distribution stable
dpkg-buildpackage: info: source changed by dev <dev@yeti-switch.org>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-checkbuilddeps: error: Unmet build dependencies: libsems1-dev (>= 1.73.0)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b -j4 failed
root@rtp-sems:/opt/yeti-sems/sems-yeti# debuild -us -uc -b -d -j$(nproc)
 dpkg-buildpackage -us -uc -ui -b -d -j4
dpkg-buildpackage: info: source package sems-yeti
dpkg-buildpackage: info: source version 1.12.18
dpkg-buildpackage: info: source distribution stable
dpkg-buildpackage: info: source changed by dev <dev@yeti-switch.org>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
 debian/rules clean
dh clean --buildsystem=cmake --builddirectory=build --parallel
   dh_auto_clean -O--buildsystem=cmake -O--builddirectory=build -O--parallel
   dh_clean -O--buildsystem=cmake -O--builddirectory=build -O--parallel
 debian/rules build
dh build --buildsystem=cmake --builddirectory=build --parallel
   dh_update_autotools_config -O--buildsystem=cmake -O--builddirectory=build -O--parallel
   dh_auto_configure -O--buildsystem=cmake -O--builddirectory=build -O--parallel
      cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Found Git: /usr/bin/git (found version "2.20.1")
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
-- Checking for one of the modules 'hiredis'
-- Found Hiredis: /usr/lib/x86_64-linux-gnu/libhiredis.so
-- Checking for module 'libsems'
--   Found libsems, version 1.40.0
-- Found SEMS: sems (found version "1.40.0")
-- Version from changelog: 1.12.18
-- git commit: 3f747d2d0ea8e16da014e0e31decf760f5807cfc
-- build date: Tue 05 Apr 2022 03:38:18 AM UTC
-- build user: root
-- version from git tags: v1.12.18
-- set version of yeti - v1.12.18
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LOCALSTATEDIR
    CMAKE_INSTALL_SYSCONFDIR


-- Build files have been written to: /opt/yeti-sems/sems-yeti/build
   dh_auto_build -O--buildsystem=cmake -O--builddirectory=build -O--parallel
      cd build && make -j4
make[1]: Entering directory '/opt/yeti-sems/sems-yeti/build'
/usr/bin/cmake -S/opt/yeti-sems/sems-yeti -B/opt/yeti-sems/sems-yeti/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /opt/yeti-sems/sems-yeti/build/CMakeFiles /opt/yeti-sems/sems-yeti/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[2]: Entering directory '/opt/yeti-sems/sems-yeti/build'
make -f CMakeFiles/sems_yeti.dir/build.make CMakeFiles/sems_yeti.dir/depend
make[3]: Entering directory '/opt/yeti-sems/sems-yeti/build'
cd /opt/yeti-sems/sems-yeti/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /opt/yeti-sems/sems-yeti /opt/yeti-sems/sems-yeti /opt/yeti-sems/sems-yeti/build /opt/yeti-sems/sems-yeti/build /opt/yeti-sems/sems-yeti/build/CMakeFiles/sems_yeti.dir/DependInfo.cmake --color=
Scanning dependencies of target sems_yeti
make[3]: Leaving directory '/opt/yeti-sems/sems-yeti/build'
make -f CMakeFiles/sems_yeti.dir/build.make CMakeFiles/sems_yeti.dir/build
make[3]: Entering directory '/opt/yeti-sems/sems-yeti/build'
[  1%] Building CXX object CMakeFiles/sems_yeti.dir/src/CallCtx.cpp.o
/usr/bin/c++  -DLOG_BUFFER_LEN=2048 -DSESSION_THREADPOOL -DUSE_LIBSAMPLERATE -DUSE_MONITORING -DUSE_SPANDSP -DWITH_ZRTP -D__STDC_LIMIT_MACROS -Dsems_yeti_EXPORTS -I/usr/include/postgresql -I/usr/include/sems -I/usr/include/sems/spandsp -I/usr/include/sems/srtp -I/opt/yeti-sems/sems-yeti/build  -g -O2 -fdebug-prefix-map=/opt/yeti-sems/sems-yeti=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC   -fmacro-prefix-map=/opt/yeti-sems/sems-yeti/src/=yeti: -D__FILENAME__=__FILE__ -I/usr/include/sems -I/usr/include/sems/spandsp -I/usr/include/sems/srtp -std=c++2a -Wno-deprecated -g -DMOD_NAME='"yeti"' -DMODULE_VERSION='"v1.12.18"' -o CMakeFiles/sems_yeti.dir/src/CallCtx.cpp.o -c /opt/yeti-sems/sems-yeti/src/CallCtx.cpp
[  3%] Building CXX object CMakeFiles/sems_yeti.dir/src/Auth.cpp.o
/usr/bin/c++  -DLOG_BUFFER_LEN=2048 -DSESSION_THREADPOOL -DUSE_LIBSAMPLERATE -DUSE_MONITORING -DUSE_SPANDSP -DWITH_ZRTP -D__STDC_LIMIT_MACROS -Dsems_yeti_EXPORTS -I/usr/include/postgresql -I/usr/include/sems -I/usr/include/sems/spandsp -I/usr/include/sems/srtp -I/opt/yeti-sems/sems-yeti/build  -g -O2 -fdebug-prefix-map=/opt/yeti-sems/sems-yeti=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC   -fmacro-prefix-map=/opt/yeti-sems/sems-yeti/src/=yeti: -D__FILENAME__=__FILE__ -I/usr/include/sems -I/usr/include/sems/spandsp -I/usr/include/sems/srtp -std=c++2a -Wno-deprecated -g -DMOD_NAME='"yeti"' -DMODULE_VERSION='"v1.12.18"' -o CMakeFiles/sems_yeti.dir/src/Auth.cpp.o -c /opt/yeti-sems/sems-yeti/src/Auth.cpp
[  5%] Building CXX object CMakeFiles/sems_yeti.dir/src/CallLeg.cpp.o
/usr/bin/c++  -DLOG_BUFFER_LEN=2048 -DSESSION_THREADPOOL -DUSE_LIBSAMPLERATE -DUSE_MONITORING -DUSE_SPANDSP -DWITH_ZRTP -D__STDC_LIMIT_MACROS -Dsems_yeti_EXPORTS -I/usr/include/postgresql -I/usr/include/sems -I/usr/include/sems/spandsp -I/usr/include/sems/srtp -I/opt/yeti-sems/sems-yeti/build  -g -O2 -fdebug-prefix-map=/opt/yeti-sems/sems-yeti=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC   -fmacro-prefix-map=/opt/yeti-sems/sems-yeti/src/=yeti: -D__FILENAME__=__FILE__ -I/usr/include/sems -I/usr/include/sems/spandsp -I/usr/include/sems/srtp -std=c++2a -Wno-deprecated -g -DMOD_NAME='"yeti"' -DMODULE_VERSION='"v1.12.18"' -o CMakeFiles/sems_yeti.dir/src/CallLeg.cpp.o -c /opt/yeti-sems/sems-yeti/src/CallLeg.cpp
[  7%] Building CXX object CMakeFiles/sems_yeti.dir/src/CertCache.cpp.o
/usr/bin/c++  -DLOG_BUFFER_LEN=2048 -DSESSION_THREADPOOL -DUSE_LIBSAMPLERATE -DUSE_MONITORING -DUSE_SPANDSP -DWITH_ZRTP -D__STDC_LIMIT_MACROS -Dsems_yeti_EXPORTS -I/usr/include/postgresql -I/usr/include/sems -I/usr/include/sems/spandsp -I/usr/include/sems/srtp -I/opt/yeti-sems/sems-yeti/build  -g -O2 -fdebug-prefix-map=/opt/yeti-sems/sems-yeti=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC   -fmacro-prefix-map=/opt/yeti-sems/sems-yeti/src/=yeti: -D__FILENAME__=__FILE__ -I/usr/include/sems -I/usr/include/sems/spandsp -I/usr/include/sems/srtp -std=c++2a -Wno-deprecated -g -DMOD_NAME='"yeti"' -DMODULE_VERSION='"v1.12.18"' -o CMakeFiles/sems_yeti.dir/src/CertCache.cpp.o -c /opt/yeti-sems/sems-yeti/src/CertCache.cpp
In file included from /opt/yeti-sems/sems-yeti/src/yeti_base.h:9,
                 from /opt/yeti-sems/sems-yeti/src/yeti_rpc.h:6,
                 from /opt/yeti-sems/sems-yeti/src/yeti.h:3,
                 from /opt/yeti-sems/sems-yeti/src/CertCache.cpp:2:
/opt/yeti-sems/sems-yeti/src/OriginationPreAuth.h:4:10: fatal error: IPTree.h: No such file or directory
 #include "IPTree.h"
          ^~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/sems_yeti.dir/build.make:105: CMakeFiles/sems_yeti.dir/src/CertCache.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/opt/yeti-sems/sems-yeti/build'
make[2]: *** [CMakeFiles/Makefile2:76: CMakeFiles/sems_yeti.dir/all] Error 2
make[2]: Leaving directory '/opt/yeti-sems/sems-yeti/build'
make[1]: *** [Makefile:133: all] Error 2
make[1]: Leaving directory '/opt/yeti-sems/sems-yeti/build'
dh_auto_build: cd build && make -j4 returned exit code 2
make: *** [debian/rules:9: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b -d -j4 failed

**Comment by furmur** [comment]
starting from version `1.11.31` the yeti module requires minimal libsems1 version `1.64.0` to build.
you are trying to compile with ancient libsems1 version `1.40.0`
